# Generated by Django 5.1.4 on 2025-01-04 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_picture.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
